# Generated by Django 6.0.5 on 2026-05-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
